Ensure failure to run `bin/activate-hermit` is propagated

diff --git a/hooks/post-checkout b/hooks/post-checkout
--- a/hooks/post-checkout
+++ b/hooks/post-checkout
@@ -3,4 +3,9 @@
 set -euo pipefail
 
 echo "~~~ Init Hermit environment"
-. bin/activate-hermit && export PATH="$PATH:/var/lib/buildkite-agent/bin"
+if ! . bin/activate-hermit; then
+  echo "Failed to initialize Hermit environment"
+  exit 1
+fi
+
+export PATH="$PATH:/var/lib/buildkite-agent/bin"
